### ISSUE TITLE
키보드 입력을 받는 경우

### ISSUE THREAD

**Issue by Hwnsgus** [junni01kim/PuyoPuyo_by_Java#26]
**버그 설명**
<버그 설명>
게임을 시작하고 게임 화면창 말고 다른 창을 활성화 하고 난 다음에만 키보드 입력이 가능함

**버그 생성 조건**
버그 발생 과정 재현  
1. Go to 'Game Start'
2. Click on 'another window'

**정상적인 상황**
<원래 작동해야 하는 동작>
게임 시작시 바로 키보드 입력을 받아야함

**버그 화면**
<Ui 상 버그인 경우 화면 촬영>
![화면 캡처 2024-11-06 171005](https://github.com/user-attachments/assets/b5fe9833-a80f-40cc-a3c3-f068ba42216c)
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/8b99400f-e1e2-49d6-8b3a-72e492fa8d2c">

**테스트 기종(please complete the following information):**
 - OS:  windows 11
 - Browser: Vscode, IntelliJ

**Comment by junni01kim** [comment]
키보드 조작을 하는 Main 스레드로 설정, 하지만 이후 RoundThread와 GameThread가 생성되면서, 키보드 requestFocus가 자동으로 이동됨. <br>
결과적으로 GameThread가 생성된 후, 해당 스레드에 requestFocus를 주입
